CREATE TABLE short_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(6) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_short_urls_short_code UNIQUE (short_code)
);

CREATE INDEX idx_short_urls_short_code ON short_urls (short_code);
CREATE INDEX idx_short_urls_original_url ON short_urls (original_url);
